name: mime_type
version: 1.0.0
authors:
    - Terry Mitsuoka <TerryMitsuoka@gmail.com>
    - Robert Beyer <4sternrb@googlemail.com>
    - Leo rignaneseleo <dev.rignaneseleo@gmail.com>
description: MIME type library for Dart HTTP server applications.
homepage: https://github.com/mitsuoka/mime_type
environment:
    sdk: '>=2.12.0 <3.0.0'
